apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: wordpress-frontend
  labels:
    app: wordpress
spec:
  template:
    metadata:
      labels:
        app: wordpress
        service: frontend
    spec:
      containers:
        - name: wordpress-container
          image: wordpress:4.8
          env:
            - name: WORDPRESS_DB_HOST
              value: wordpress-mysql
            - name: WORDPRESS_DB_PASSWORD
              value: P@ssw0rd
          ports:
            - containerPort: 80
              name: wordpress-port
          volumeMounts:
            - name: wordpress-volume
              mountPath: /var/www/html
      volumes:
        - name: wordpress-volume
          persistentVolumeClaim:
            claimName: wordpress-pvc
